PullRequest01
OldM1lk/sem2Lab05-Strings-and-Collections- pull request #1
Opened 2024-03-06 10:23 UTC by OldM1lk

2024-03-06 16:28 UTC, iredb requested changes

2024-03-06 16:28 UTC, iredb commented on CODE.cs
> +      string phoneNumber = match.Value;
![image](https://github.com/OldM1lk/sem2Lab05-Strings-and-Collections-/assets/120615742/7699865c-b461-4c4f-8129-a7958c1d9009)

2024-03-06 16:28 UTC, iredb commented on CODE.cs
> +        MatchCollection matches = Regex.Matches(fileContent, numberToFind);
![image](https://github.com/OldM1lk/sem2Lab05-Strings-and-Collections-/assets/120615742/cef672eb-c5a6-4fc9-b3ec-ae5078730421)

2024-03-06 16:28 UTC, iredb commented on CODE.cs
> +      string[] filesInPath = Directory.GetFiles(directoryPath, "*.txt");
filesInDirectory

2024-03-07 00:41 UTC, OldM1lk commented on CODE.cs
> +      string directoryPath = Console.ReadLine();
исправил

2024-03-07 00:46 UTC, OldM1lk commented on CODE.cs
> +      string phoneNumber = match.Value;
использовал

2024-03-07 00:47 UTC, OldM1lk commented on CODE.cs
> +      string[] filesInPath = Directory.GetFiles(directoryPath, "*.txt");
исправил

2024-03-07 01:01 UTC, OldM1lk commented on CODE.cs
> +        MatchCollection matches = Regex.Matches(fileContent, numberToFind);
?

2024-03-07 03:01 UTC, OldM1lk commented on CODE.cs
> +        MatchCollection matches = Regex.Matches(fileContent, numberToFind);
исправлено

2024-03-07 09:09 UTC, closed without merging

2024-03-07 09:10 UTC, OldM1lk commented
Unluck